AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  safe-scheme-api
Transform: 'AWS::Serverless-2016-10-31'  # Should be a string, not an array

Resources:
  createProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/create-project.createProjectHandler
      Description: Create project function
      Policies:
        # Give Create/Read/Update/Delete Permissions to the ProjectsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /create-project
            Method: POST

  getProjectsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/get-projects.getProjectsHandler
      Description: Get user projects function
      Policies:
        # Same policy for DynamoDB CRUD operations
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /get-project
            Method: GET

  deleteProjectFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handlers/delete-project.deleteProjectHandler
      Description: Delete projects function
      Policies:
        # Same policy for DynamoDB CRUD operations
        - DynamoDBCrudPolicy:
            TableName: !Ref ProjectsTable
      Events:
        Api:
          Type: Api
          Properties:
            Path: /delete-project
            Method: DELETE

  ProjectsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ProjectsTable
      AttributeDefinitions:
        - AttributeName: user-id
          AttributeType: S  # String type for partition key
        - AttributeName: project-id
          AttributeType: S  # String type for sort key
      KeySchema:
        - AttributeName: user-id
          KeyType: HASH  # Partition key
        - AttributeName: project-id
          KeyType: RANGE # Sort key
      ProvisionedThroughput:
        ReadCapacityUnits: 2
        WriteCapacityUnits: 2

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name:
        Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName:
        Ref: ApplicationResourceGroup
      AutoConfigurationEnabled: 'true'

Outputs:
  WebEndpoint:
    Description: API Gateway endpoint URL for Prod stage
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
      - x86_64
    MemorySize: 128
    Tracing: Active
    Timeout: 100
    Environment:
      Variables:
        PROJECTS_TABLE: !Ref ProjectsTable # Accessible as an env var from Lambda
        DYNAMODB_ENDPOINT: https://localhost:8000
    LoggingConfig:
      LogFormat: JSON
  Api:
    TracingEnabled: true
