type: object
properties:
  id:
    type: string
    description: The unique identifier for the project
  name:
    type: string
    description: The name of the project
  description:
    type: string
    description: A brief description of the project
  tasks:
    type: array
    items:
      $ref: "./task.yaml"
    description: A list of tasks associated with the project
  createdAt:
    type: string
    format: date-time
    description: The date and time when the project was created
required:
  - id
  - name