openapi: 3.1.0
info:
  title: Safe-Scheme
  description: Safe-Scheme API specification
  version: 1.0.0
servers:
  - url: 'https://localhost:3000'
paths:
  /create-project:
    $ref: './api/create-projects.yaml'
  /get-projects:
    $ref: './api/get-projects.yaml'


components:
  schemas:
    Project:
      $ref: './components/schemas/project.yaml'
    Task:
      $ref: './components/schemas/task.yaml'
